db:
  credentials_file: "configs/google-service-account.json"
  spreadsheet_id: "YOUR_SPREADSHEET_ID_HERE"
  cashbacks_sheet: "Cashbacks"
  categories_sheet: "Categories"
  cards_sheet: "Cards"

vlm:
  api_token: "YOUR_VLM_API_TOKEN_HERE"
  base_url: "VLM_PROVIDER_URL"
  model_name: "MODEL_NAME"
  prompt_template_file: "PATH_TO_YOUR_TEMPLATE_FILE.md"
  sampling_params:
    max_tokens: 512
    temperature: 0.2
    top_p: 0.9

bot:
  token: "YOUR_BOT_TOKEN_HERE"
  users:
    - tg_username: "YOUR_TG_USERNAME"
      db_username: "YOUR_DB_USERNAME"
    - tg_username: "YOUR_TG_USERNAME"
      db_username: "YOUR_DB_USERNAME"

  images_path: "YOUR_IMAGES_PATH"
  state_path: "data/bot_state.pkl"

  messages:
    start_message: "Выберите действие или отправьте скриншот с категориями кэшбэка 📱"
    refuse_message: "Для этого аккаунта доступ к боту не настроен."
    processing_message: "Скриншот обрабатывается… 🔄"
    ok_message: "Категории распознаны."
    continue_message: "Можно отправить следующий скриншот 📨"
    not_ok_message: "Не удалось обработать запрос. Попробуйте ещё раз."
    empty_list_message: "На выбранный месяц кэшбэков пока нет 🤷"
